/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "wtf.h"

int main(void)
{
	GPIO_Handle_t handle;
	handle.config.output_speed = GPIO_SPEED_LOW;
//	handle.config.ouput_type = GPIO_PUSH_PULL;
	handle.config.PUPD = GPIO_NPUPD;
	handle.config.mode_type = GPIO_MODE_OUTPUT;
	handle.config.pin_number = 0;

	omg();
	handle.pGPIOPad = GPIOA;
	test();
	GPIO_Init(&handle);

	GPIO_IRQConfig(&handle);

    /* Loop forever */
	for(;;);
}

void EXTI0_IRQHandler(void)
{

}
